---
language: ruby
rvm:
- 1.9.3
after_script:
- gem install heroku
- git remote add heroku git@heroku.com:obscure-plains-8681.git
- yes | ruby travis_deployer.rb
- heroku keys:clear
- yes | heroku keys:add
- git push heroku master
env:
  global:
  - secure: ! 'bssjutolAlN3EgSATuTjCI9X90aOxe4jpte2RjHWkH4JWiXKnZsyuTdcDwlgHLLhJ7b3gG8iinCxKgnITw+feVIlG8Zzs72VMRLHjGgs9JetHqex/Z7kKmwSBNyhQ4FUJuoYTaNRDn+mwP/6RnJtOPyEUNpw5rq2kvlDggpbnWo='
